config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'admin_sessions/new'
  root to: 'parcom#index'

  get 'sessions/new'
  resources :schedules

  # get '/zyzw', to: 'admin#index' #（例）adminログイン画面のURLを特定されない名前にする
  get '/admin_login',   to: 'admin_sessions#new'
  post '/admin_login',   to: 'admin_sessions#create'
  delete '/admin_logout',  to: 'admin_sessions#destroy'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'admin/index'
  post 'admin/index'
  get 'admin/add'
  post 'admin/add'
  get 'admin/add_done'
  get 'admin/edit'
  post 'admin/edit'
  patch 'admin/edit'
  get 'admin/delete'
  post 'admin/delete'
  get 'admin/delete_done'
  get 'admin/command'

  get 'index', to: 'parcom#index'
  get 'beginners', to: 'parcom#beginners'
  get 'help', to: 'parcom#help'
  get 'privacy', to: 'parcom#privacy'
  get 'terms', to: 'parcom#terms'
  get 'article', to: 'parcom#article'
  get 'free_wifi', to: 'parcom#free_wifi'
  get 'news', to: 'parcom#news'
  get 'park/:park_id', to: 'parcom#park'
  get 'profile/:park_id', to: 'parcom#profile'
  get 'review/:park_id', to: 'parcom#review'
  get 'parcom/get_data'
  get 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'parcom/create'
  resources :parcom, only: [:new, :create]

  get 'parcom/post_data'
  post 'parcom/post_data'
  
  get '/', to: 'parcom#index'
  post '/', to: 'parcom#index'
  get 'index', to: 'parcom#index'
  get 'register', to: 'user#register'
  post 'register', to: 'user#register'
  get 'user/create', to: 'user#create'
  post 'user/create', to: 'user#create'
  get 'account', to: 'user#account'
  post 'account', to: 'user#account'
  patch 'account', to: 'user#account'
  get 'changemail', to: 'user#changemail'
  patch 'changemail', to: 'user#changemail'
  get 'changepwd', to: 'user#changepwd'
  post 'changepwd', to: 'user#changepwd'
  patch 'changepwd', to: 'user#changepwd'
  get 'signup_success', to: 'user#signup_success'
  post 'signup_success', to: 'user#signup_success'
  get 'signupmail_success', to: 'user#signupmail_success'
  get 'signupmail', to: 'user#signupmail'
  post 'signupmail', to: 'user#signupmail'
  get 'signupmail_error', to: 'user#signupmail_error'
  get 'user/signupmail_confirm'
  post 'user/signupmail_confirm'
  post 'user/back'
  get 'changepwd_success', to: 'user#changepwd_success'
  get 'changepwd_error', to: 'user#changepwd_error'
  get 'not_activated', to: 'user#not_activated'
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/mail_done'
  get 'password_resets/mail_error'
  get 'password_resets/success'

  get 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  post 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  patch 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  get 'products/:park_id', to: 'park#products'
  resources :park, only: [:new, :create]
  
  get 'shortcut/:park_id', to: 'shortcut#index'
  post 'shortcut/create', to: 'shortcut#create'
  post 'shortcut/delete/:shortcut_id', to: 'shortcut#delete'

  get 'contacts', to: 'contacts#new'
  resources :contacts, only: [:create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'

  get 'analyze/:park_id', to: 'analyze#index'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"
  
end

app/views/admin/_not_logged_in.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<h1>Please log in to start PARCOM ADMIN</h1>
<%= link_to "ADMINにログインする>>", admin_login_path %>

app/views/admin/add.html.erb
<br>
<br>
<br>
<br>
<br>
<p id="admin_title">DBにデータを追加する</p>

<div id="contents">
<div class="back"><%= link_to "ADMINからログアウトする>>", admin_logout_path, method: :delete %></div>
<br>
<div class="back"><a href="/admin/index">adminトップに戻る>></a></div>
<br>
<div class="back"><a href="/admin/command">ベンチを指定してコマンドを送る>></a></div>
<br>
<p>追加したいモデルを選択してフォームを表示</p>

<%= form_with url: 'add',local:false do |form| %>
    <%= form.select(:category, ["ユーザー", "公園", "ベンチ", "写真", "イベント", "ショートカット", "ベンチ用PDF", "ベンチ用MP4", "ベンチ用MP3"],{}, required: true, id:'model_select') %>
    <%= form.submit "表示", id: "model_submit" %>
<% end %>

<div class="table_name" id="user">
<h2>ユーザーのデータを作成</h2>
<%= form_for(@user, url:{controller:'admin', action:'add'}) do |form| %>
    <div class="form-group">
        <label for="name">表示名</label>
        <%= form.text_field :name, class:"form" %>
    </div>
    <div class="form-group">
        <label for="email">メールアドレス</label>
        <%= form.email_field :email, class:"form" %>
    </div>
    <div class="form-group">
        <label for="zip">郵便番号</label>
        <%= form.text_field :zip, class:"form" %>
    </div>
    <div class="form-group">
        <label for="prefecture">住所(都道府県)</label>
        <%= form.text_field :prefecture, class:"form" %>
    </div>
    <div class="form-group">
        <label for="city">住所(市区町村)</label>
        <%= form.text_field :city, class:"form" %>
    </div>
    <div class="form-group">
        <label for="street">それ以降の住所</label>
        <%= form.text_field :street, class:"form" %>
    </div>
    <div class="form-group">
        <label for="tel">電話番号</label>
        <%= form.text_field :tel, class:"form" %>
    </div>
    <div class="form-group">
        <label for="municipality">自治体名</label>
        <%= form.text_field :municipality, class:"form" %>
    </div>
    <div class="form-group">
        <label for="division">所属課</label>
        <%= form.text_field :division, class:"form" %>
    </div>
    <div class="form-group">
        <label for="image">プロフィール画像</label>
        <%= form.text_field :image, class:"form" %>
    </div>
    <div class="form-group">
        <label for="profile">プロフィール内容</label>
        <%= form.text_field :profile, class:"form" %>
    </div>
    <div class="form-group">
        <label for="notification">メール通知設定</label>
        <%= form.text_field :notification, class:"form" %>
    </div>
    <div class="form-group">
        <label for="flag">通知フラグ</label>
        <%= form.text_field :flag, class:"form" %>
    </div>
    <div class="form-group">
        <label for="admin_memo">管理者メモ</label>
        <%= form.text_field :admin_memo, class:"form" %>
    </div>
    <div class="make_model_wrap"><%= form.submit "作成", class:"make_model_btn" %></div>
<% end %>
</div>


<div class="table_name" id="park">
<h2>公園のデータを作成</h2>
<%= form_for(@park, url:{controller:'admin', action:'add'}) do |form| %>
    <div class="form-group">
        <label for="name">公園名</label>
        <%= form.text_field :name, class:"form" %>
    </div>
    <div class="form-group">
        <label for="zip">郵便番号</label>
        <%= form.text_field :zip, class:"form" %>
    </div>
    <div class="form-group">
        <label for="prefecture">住所(都道府県)</label>
        <%= form.text_field :prefecture, class:"form" %>
    </div>
    <div class="form-group">
        <label for="city">住所(市区町村)</label>
        <%= form.text_field :city, class:"form" %>
    </div>
    <div class="form-group">
        <label for="street">それ以降の住所</label>
        <%= form.text_field :street, class:"form" %>
    </div>
    <div class="form-group">
        <label for="hours">営業時間</label>
        <%= form.text_field :hours, class:"form" %>
    </div>
    <div class="form-group">
        <label for="tel">電話番号</label>
        <%= form.text_field :tel, class:"form" %>
    </div>
    <div class="form-group">
        <label for="fee">入場料金</label>
        <%= form.text_field :fee, class:"form" %>
    </div>
    <div class="form-group">
        <label for="map">Google MapのURL</label>
        <%= form.text_field :map, class:"form" %>
    </div>
    <div class="form-group">
        <label for="website">公式ホームページのURL</label>
        <%= form.text_field :website, class:"form" %>
    </div>
    <div class="form-group">
        <label for="size">面積</label>
        <%= form.text_field :size, class:"form" %>
    </div>
    <div class="form-group">
        <label for="profile">紹介文</label>
        <%= form.text_field :profile, class:"form" %>
    </div>
    <div class="form-group">
        <label for="parking_info">駐車場情報</label>
        <%= form.text_field :parking_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="toilet_info">トイレ情報</label>
        <%= form.text_field :toilet_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="playground_info">遊具情報</label>
        <%= form.text_field :playground_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="facility_info">施設情報</label>
        <%= form.text_field :facility_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="sports_info">スポーツ情報</label>
        <%= form.text_field :sports_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="view_info">景観情報</label>
        <%= form.text_field :view_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="disaster_info">防災情報</label>
        <%= form.text_field :disaster_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="other_info">その他情報</label>
        <%= form.text_field :other_info, class:"form" %>
    </div>
    <div class="form-group">
        <label for="iframe">地図のiframeURL</label>
        <%= form.text_field :iframe, class:"form" %>
    </div>
    <div class="make_model_wrap"><%= form.submit "作成", class:"make_model_btn" %></div>
<% end %>
</div>


<div class="table_name" id="bench">
<h2>ベンチのデータを作成</h2>
<%= form_for(@bench, url:{controller:'admin', action:'add'}) do |form| %>
    <div class="form-group">
        <label for="park_id">所属公園ID</label>
        <%= form.text_field :park_id, class:"form" %>
    </div>
    <div class="form-group">
        <label for="name">ベンチ名</label>
        <%= form.text_field :name, class:"form" %>
    </div>
    <div class="form-group">
        <label for="mac_address">MACアドレス</label>
        <%= form.text_field :mac_address, class:"form" %>
    </div>
    <div class="form-group">
        <label for="os_name">OS</label>
        <%= form.text_field :os_name, class:"form" %>
    </div>
    <div class="form-group">
        <label for="mac_address">導入日（例: 2022-01-01）</label>
        <%= form.text_field :introduced_date, class:"form" %>
    </div>
    <div class="make_model_wrap"><%= form.submit "作成", class:"make_model_btn" %></div>
<% end %>
</div>


<div class="table_name" id="picture">
<h2>写真のデータを作成</h2>
<%= form_for(@picture, url:{controller:'admin', action:'add'}) do |form| %>
    <div class="form-group">
        <label for="park_id">所属公園ID</label>
        <%= form.text_field :park_id, class:"form" %>
    </div>
    <div class="form-group">
        <label for="name">写真のタイトル</label>
        <%= form.text_field :name, class:"form" %>
    </div>
    <div class="form-group">
        <label for="picture">写真</label>
        <%= form.text_field :picture, class:"form" %>
    </div>
    <div class="make_model_wrap"><%= form.submit "作成", class:"make_model_btn" %></div>
<% end %>
</div>


<div class="table_name" id="event">
<h2>イベントのデータを作成</h2>
<%= form_for(@event, url:{controller:'admin', action:'add'}) do |form| %>
    <div class="form-group">
        <label for="park_id">所属公園ID</label>
        <%= form.text_field :park_id, class:"form" %>
    </div>
    <div class="form-group">
        <label for="name">イベント名</label>
        <%= form.text_field :name, class:"form" %>
    </div>
    <div class="form-group">
        <label for="image">写真</label>
        <%= form.text_field :image, class:"form" %>
    </div>
    <div class="form-group">
        <label for="contents">説明</label>
        <%= form.text_field :contents, class:"form" %>
    </div>
    <div class="make_model_wrap"><%= form.submit "作成", class:"make_model_btn" %></div>
<% end %>
</div>


<div class="table_name" id="shortcut">
<h2>ショートカットのデータを作成</h2>
<%= form_for(@shortcut, url:{controller:'admin', action:'add'}) do |form| %>
    <div class="form-group">
        <label for="park_id">ショートカットを登録する公園のID</label>
        <%= form.text_field :park_id, class:"form" %>
    </div>
    <div class="form-group">
        <label for="nickname">ショートカット名</label>
        <%= form.text_field :nickname, class:"form" %>
    </div>
    <div class="form-group">
        <label for="start_time">開始時間</label>
        <%= form.text_field :start_time, class:"form" %>
    </div>
    <div class="form-group">
        <label for="end_time">終了時間</label>
        <%= form.text_field :end_time, class:"form" %>
    </div>
    <div class="form-group">
        <label for="repeat">リピート有無</label>
        <%= form.text_field :repeat, class:"form" %>
    </div>
    <div class="form-group">
        <label for="program">プログラム内容</label>
        <%= form.text_field :program, class:"form" %>
    </div>
    <div class="make_model_wrap"><%= form.submit "作成", class:"make_model_btn" %></div>
<% end %>
</div>
<br>
<br>
<br>
<br>
<br>

<script>
let model_select = document.getElementById('model_select');
let model_submit = document.getElementById('model_submit');
model_select.addEventListener('change', function(e) {
    model_submit.click();
});

let models = ['user', 'park', 'bench', 'picture', 'event', 'shortcut', 'bench_image', 'bench_video', 'bench_audio'];
for(let i = 0; i < tables.length; i++){
    if(hidden_model.textContent == models[i]){
        model_select.options[i+1].selected = true;
        tables[i].style.display = 'block';
    }
}

</script>

app/views/admin/add.js.erb
$('.table_name').css({'display':'none'});

result = "<%= @result %>";

if(result == 'ユーザー'){
    $('#user').css({'display':'block'});
} else if(result == '公園'){
    $('#park').css({'display':'block'});
} else if(result == 'ベンチ'){
    $('#bench').css({'display':'block'});
} else if(result == 'お知らせ'){
    $('#news').css({'display':'block'});
} else if(result == 'メディア情報'){
    $('#media').css({'display':'block'});
} else if(result == '写真'){
    $('#picture').css({'display':'block'});
} else if(result == 'イベント'){
    $('#event').css({'display':'block'});
} else if(result == 'プロダクト'){
    $('#product').css({'display':'block'});
} else if(result == 'ショートカット'){
    $('#shortcut').css({'display':'block'});
} else if(result == 'ベンチからのデータ'){
    $('#tmp_data').css({'display':'block'});
} else if(result == 'ベンチへのコマンド'){
    $('#tmp_message').css({'display':'block'});
}

app/views/admin/add_done.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<p id="admin_title">データを追加しました！</p>
<p class="back"><a href="/admin/index">adminトップに戻る>></a></p>

app/views/admin/command.html.erb
<p id="admin_title">ベンチを指定してコマンドを送る</p>

<div id="contents">
    <p class="back"><a href="/admin/index">adminトップに戻る>></a></p>
    <br>
    <p>ベンチを選択</p>
    <% if @benches %>
        <select id="bench_mac_adrs">
            <option value="">ベンチを選択してください</option>
            <% @benches.each do |bench| %>
                <option value="<%= bench.mac_address %>"><%= bench.name %> （ MACアドレス: <%= bench.mac_address %> ）</option>
            <% end %>
        </select>
        <% else %>
        <p>登録されているスマートベンチはありません。</p>
    <% end %>
    <p class="hidden" id="hidden_mac_adrs"></p>
    <br>
    <br>
    <br>
    <br>

    <p>USB用5V電源供給を許可ON/OFFします</p>
    <button class="usb_btn">ON</button>
    <button class="usb_btn">OFF</button>
    <br>
    <br>
    <p>ラズパイターミナル画面へのログ出力をON/OFFします</p>
    <button class="log_btn">ON</button>
    <button class="log_btn">OFF</button>
    <br>
    <br>
    <p>Smart Benchの位置（緯度、経度）を手動で設定</p>
    <input id="lat" type="number" class="position_default">
    <input id="lon" type="number" class="position_default">
    <button id="position_btn">設定</button>
    <br>
    <br>
    <p>システムを停止します。プログラムの修正や追加の作業を行う際に指定します。</p>
    <button id="systemdown_btn">システム停止</button>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<%= javascript_pack_tag 'admin' %>

app/views/admin/delete.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<p id="admin_title">データ削除 確認画面</p>
<div id="contents">
    <div class="back"><%= link_to "ADMINからログアウトする>>", admin_logout_path, method: :delete %></div>
    <br>
    <div class="back"><a href="/admin/index">adminトップに戻る>></a></div>
    <br>
    <div class="back"><a href="/admin/command">ベンチを指定してコマンドを送る>></a></div>

<% if @user != nil %>
    <p>以下のデータを削除してもいいですか？</p>
    <br><div class="table_wrap">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>権限</th>
            <th>登録日時</th>
            <th>ユーザーID(不要？)</th>
            <th>表示名</th>
            <th>メールアドレス</th>
            <th>郵便番号</th>
            <th>住所(都道府県)</th>
            <th>住所(市区町村)</th>
            <th>それ以降の住所</th>
            <th>電話番号</th>
            <th>自治体名</th>
            <th>所属課</th>
            <th>プロフィール画像</th>
            <th>プロフィール内容</th>
            <th>メール通知設定</th>
            <th>通知フラグ</th>
            <th>管理者メモ</th>
        </tr>
        <tr>
            <td><%= @user.id %></td>
            <td><%= @user.name %></td>
            <td><%= @user.email %></td>
            <td><%= @user.zip %></td>
            <td><%= @user.prefecture %></td>
            <td><%= @user.address %></td>
            <td><%= @user.street %></td>
            <td><%= @user.tel %></td>
            <td><%= @user.municipality %></td>
            <td><%= @user.division %></td>
            <td><%= @user.image %></td>
            <td><%= @user.profile %></td>
            <td><%= @user.notification %></td>
            <td><%= @user.flag %></td>
            <td><%= @user.admin_memo %></td>
        </tr>
    </table>
    <%= form_tag('delete') do %>
        <%= text_field_tag 'user_delete_id', @user.id , class: 'edit_id' %>
        <%= button_to '削除'%>
    <% end %>

<% elsif @park != nil %>
    <p>以下のデータを削除してもいいですか？</p>
    <br><div class="table_wrap">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>ユーザーID</th>
            <th>作成日時</th>
            <th>ステータス</th>
            <th>公園名</th>
            <th>郵便番号</th>
            <th>住所(都道府県)</th>
            <th>住所(市区町村)</th>
            <th>それ以降の住所</th>
            <th>営業時間</th>
            <th>電話番号</th>
            <th>入場料金</th>
            <th>Google Map</th>
            <th>公式ホームページ</th>
            <th>面積</th>
            <th>紹介文</th>
            <th>状況</th>
            <th>駐車場情報</th>
            <th>トイレ情報</th>
            <th>遊具情報</th>
            <th>施設情報</th>
            <th>スポーツ情報</th>
            <th>景観情報</th>
            <th>防災情報</th>
            <th>その他情報</th>
        </tr>
        <tr>
            <td><%= @park.id %></td>
            <td><%= @park.user_id %></td>
            <td><%= @park.name %></td>
            <td><%= @park.zip %></td>
            <td><%= @park.prefecture %></td>
            <td><%= @park.address %></td>
            <td><%= @park.street %></td>
            <td><%= @park.hours %></td>
            <td><%= @park.tel %></td>
            <td><%= @park.fee %></td>
            <td><%= @park.map %></td>
            <td><%= @park.website %></td>
            <td><%= @park.size %></td>
            <td><%= @park.profile %></td>
            <td><%= @park.status %></td>
            <td><%= @park.parking_info %></td>
            <td><%= @park.toilet_info %></td>
            <td><%= @park.playground_info %></td>
            <td><%= @park.facility_info %></td>
            <td><%= @park.sports_info %></td>
            <td><%= @park.view_info %></td>
            <td><%= @park.disaster_info %></td>
            <td><%= @park.other_info %></td>
        </tr>
    </table>
    <%= form_tag('delete') do %>
        <%= text_field_tag 'park_delete_id', @park.id , class: 'edit_id' %>
        <%= button_to '削除'%>
    <% end %>

<% elsif @bench != nil %>
    <p>以下のデータを削除してもいいですか？</p>
    <br><div class="table_wrap">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>所属公園ID</th>
            <th>ベンチ名</th>
            <th>MACアドレス</th>
            <th>OS</th>
            <th>導入日</th>
            <th>位置情報</th>
            <th>タイマーON/OFF</th>
        </tr>
        <tr>
            <td><%= @bench.id %></td>
            <td><%= @bench.park_id %></td>
            <td><%= @bench.name %></td>
            <td><%= @bench.mac_address %></td>
            <td><%= @bench.os_name %></td>
            <td><%= @bench.introduced_date %></td>
            <td><%= @bench.position %></td>
            <td><%= @bench.timer %></td>
        </tr>
    </table>
    <%= form_tag('delete') do %>
        <%= text_field_tag 'bench_delete_id', @bench.id , class: 'edit_id' %>
        <%= button_to '削除'%>
    <% end %>

<% elsif @picture != nil %>
    <p>以下のデータを削除してもいいですか？</p>
    <br><div class="table_wrap">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>所属公園ID</th>
            <th>写真のタイトル</th>
            <th>写真</th>
        </tr>
        <tr>
            <td><%= @picture.id %></td>
            <td><%= @picture.park_id %></td>
            <td><%= @picture.name %></td>
            <td><%= @picture.picture %></td>
        </tr>
    </table>
    <%= form_tag('delete') do %>
        <%= text_field_tag 'picture_delete_id', @picture.id , class: 'edit_id' %>
        <%= button_to '削除'%>
    <% end %>

<% elsif @event != nil %>
    <p>以下のデータを削除してもいいですか？</p>
    <br><div class="table_wrap">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>所属公園ID</th>
            <th>イベント名</th>
            <th>説明</th>
        </tr>
        <tr>
            <td><%= @event.id %></td>
            <td><%= @event.park_id %></td>
            <td><%= @event.name %></td>
            <td><%= @event.contents %></td>
        </tr>
    </table>
    <%= form_tag('delete') do %>
        <%= text_field_tag 'event_delete_id', @event.id , class: 'edit_id' %>
        <%= button_to '削除'%>
    <% end %>

<% elsif @product != nil %>
    <p>以下のデータを削除してもいいですか？</p>
    <br><div class="table_wrap">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>所属公園ID</th>
            <th>プロダクト名</th>
            <th>説明</th>
        </tr>
        <tr>
            <td><%= @product.id %></td>
            <td><%= @product.park_id %></td>
            <td><%= @product.name %></td>
            <td><%= @product.contents %></td>
        </tr>
    </table>
    <%= form_tag('delete') do %>
        <%= text_field_tag 'product_delete_id', @product.id , class: 'edit_id' %>
        <%= button_to '削除'%>
    <% end %>

<% elsif @shortcut != nil %>
    <p>以下のデータを削除してもいいですか？</p>
    <br><div class="table_wrap">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>ベンチID</th>
            <th>ショートカット名</th>
            <th>プログラム内容</th>
            <th>導入日</th>
        </tr>
        <tr>
            <td><%= @shortcut.id %></td>
            <td><%= @shortcut.bench_id %></td>
            <td><%= @shortcut.name %></td>
            <td><%= @shortcut.program %></td>
            <td><%= @shortcut.introduced_date %></td>
        </tr>
    </table>
    <%= form_tag('delete') do %>
        <%= text_field_tag 'shortcut_delete_id', @shortcut.id , class: 'edit_id' %>
        <%= button_to '削除'%>
    <% end %>
<% else %>
    <h2>トップページからしか削除対象を指定できません。トップページから操作をやり直してください。</h2>
<% end %>

app/views/admin/delete_done.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<p id="admin_title">削除が完了しました！</p>
<p class="back"><a href="/admin/index">adminトップに戻る>></a></p>

app/views/admin/index.html.erb
<h1>ADMIN</h1>
<% if admin_logged_in? %>
  <%= render 'admin/logged_in' %>
<% else %>
  <%= render 'admin/not_logged_in' %>
<% end %>

app/views/admin/index.js.erb
$('#hidden_model').text("<%= @model %>");