config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'admin_sessions/new'
  root to: 'parcom#index'

  get 'sessions/new'
  resources :schedules

  # get '/zyzw', to: 'admin#index' #（例）adminログイン画面のURLを特定されない名前にする
  get '/admin_login',   to: 'admin_sessions#new'
  post '/admin_login',   to: 'admin_sessions#create'
  delete '/admin_logout',  to: 'admin_sessions#destroy'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'admin/index'
  post 'admin/index'
  get 'admin/add'
  post 'admin/add'
  get 'admin/add_done'
  get 'admin/edit'
  post 'admin/edit'
  patch 'admin/edit'
  get 'admin/delete'
  post 'admin/delete'
  get 'admin/delete_done'
  get 'admin/command'

  get 'index', to: 'parcom#index'
  get 'beginners', to: 'parcom#beginners'
  get 'help', to: 'parcom#help'
  get 'privacy', to: 'parcom#privacy'
  get 'terms', to: 'parcom#terms'
  get 'article', to: 'parcom#article'
  get 'free_wifi', to: 'parcom#free_wifi'
  get 'news', to: 'parcom#news'
  get 'park/:park_id', to: 'parcom#park'
  get 'profile/:park_id', to: 'parcom#profile'
  get 'review/:park_id', to: 'parcom#review'
  get 'parcom/get_data'
  get 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'parcom/create'
  resources :parcom, only: [:new, :create]

  get 'parcom/post_data'
  post 'parcom/post_data'
  
  get '/', to: 'parcom#index'
  post '/', to: 'parcom#index'
  get 'index', to: 'parcom#index'
  get 'register', to: 'user#register'
  post 'register', to: 'user#register'
  get 'user/create', to: 'user#create'
  post 'user/create', to: 'user#create'
  get 'account', to: 'user#account'
  post 'account', to: 'user#account'
  patch 'account', to: 'user#account'
  get 'changemail', to: 'user#changemail'
  patch 'changemail', to: 'user#changemail'
  get 'changepwd', to: 'user#changepwd'
  post 'changepwd', to: 'user#changepwd'
  patch 'changepwd', to: 'user#changepwd'
  get 'signup_success', to: 'user#signup_success'
  post 'signup_success', to: 'user#signup_success'
  get 'signupmail_success', to: 'user#signupmail_success'
  get 'signupmail', to: 'user#signupmail'
  post 'signupmail', to: 'user#signupmail'
  get 'signupmail_error', to: 'user#signupmail_error'
  get 'user/signupmail_confirm'
  post 'user/signupmail_confirm'
  post 'user/back'
  get 'changepwd_success', to: 'user#changepwd_success'
  get 'changepwd_error', to: 'user#changepwd_error'
  get 'not_activated', to: 'user#not_activated'
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/mail_done'
  get 'password_resets/mail_error'
  get 'password_resets/success'

  get 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  post 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  patch 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  get 'products/:park_id', to: 'park#products'
  resources :park, only: [:new, :create]
  
  get 'shortcut/:park_id', to: 'shortcut#index'
  post 'shortcut/create', to: 'shortcut#create'
  post 'shortcut/delete/:shortcut_id', to: 'shortcut#delete'

  get 'contacts', to: 'contacts#new'
  resources :contacts, only: [:create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'

  get 'analyze/:park_id', to: 'analyze#index'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"
  
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :logged_in_user
  before_action :set_schedule, only: %i[ show edit update destroy ]

  # GET /schedules or /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        ShortcutJob.set(wait_until: @schedule.start_time).perform_later(@schedule.id)
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:title, :start_time, :end_time)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<br>
<br>
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>
<br>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.title %></td>
        <td><%= schedule.start_time %></td>
        <td><%= schedule.end_time %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @schedule.title %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>