config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'admin_sessions/new'
  root to: 'parcom#index'

  get 'sessions/new'
  resources :schedules

  # get '/zyzw', to: 'admin#index' #（例）adminログイン画面のURLを特定されない名前にする
  get '/admin_login',   to: 'admin_sessions#new'
  post '/admin_login',   to: 'admin_sessions#create'
  delete '/admin_logout',  to: 'admin_sessions#destroy'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'admin/index'
  post 'admin/index'
  get 'admin/add'
  post 'admin/add'
  get 'admin/add_done'
  get 'admin/edit'
  post 'admin/edit'
  patch 'admin/edit'
  get 'admin/delete'
  post 'admin/delete'
  get 'admin/delete_done'
  get 'admin/command'

  get 'index', to: 'parcom#index'
  get 'beginners', to: 'parcom#beginners'
  get 'help', to: 'parcom#help'
  get 'privacy', to: 'parcom#privacy'
  get 'terms', to: 'parcom#terms'
  get 'article', to: 'parcom#article'
  get 'free_wifi', to: 'parcom#free_wifi'
  get 'news', to: 'parcom#news'
  get 'park/:park_id', to: 'parcom#park'
  get 'profile/:park_id', to: 'parcom#profile'
  get 'review/:park_id', to: 'parcom#review'
  get 'parcom/get_data'
  get 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'parcom/create'
  resources :parcom, only: [:new, :create]

  get 'parcom/post_data'
  post 'parcom/post_data'
  
  get '/', to: 'parcom#index'
  post '/', to: 'parcom#index'
  get 'index', to: 'parcom#index'
  get 'register', to: 'user#register'
  post 'register', to: 'user#register'
  get 'user/create', to: 'user#create'
  post 'user/create', to: 'user#create'
  get 'account', to: 'user#account'
  post 'account', to: 'user#account'
  patch 'account', to: 'user#account'
  get 'changemail', to: 'user#changemail'
  patch 'changemail', to: 'user#changemail'
  get 'changepwd', to: 'user#changepwd'
  post 'changepwd', to: 'user#changepwd'
  patch 'changepwd', to: 'user#changepwd'
  get 'signup_success', to: 'user#signup_success'
  post 'signup_success', to: 'user#signup_success'
  get 'signupmail_success', to: 'user#signupmail_success'
  get 'signupmail', to: 'user#signupmail'
  post 'signupmail', to: 'user#signupmail'
  get 'signupmail_error', to: 'user#signupmail_error'
  get 'user/signupmail_confirm'
  post 'user/signupmail_confirm'
  post 'user/back'
  get 'changepwd_success', to: 'user#changepwd_success'
  get 'changepwd_error', to: 'user#changepwd_error'
  get 'not_activated', to: 'user#not_activated'
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/mail_done'
  get 'password_resets/mail_error'
  get 'password_resets/success'

  get 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  post 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  patch 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  get 'products/:park_id', to: 'park#products'
  resources :park, only: [:new, :create]
  
  get 'shortcut/:park_id', to: 'shortcut#index'
  post 'shortcut/create', to: 'shortcut#create'
  post 'shortcut/delete/:shortcut_id', to: 'shortcut#delete'

  get 'contacts', to: 'contacts#new'
  resources :contacts, only: [:create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'

  get 'analyze/:park_id', to: 'analyze#index'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"
  
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def new
        @contact = Contact.new
    end

    # 確認画面を作成する場合はこのような記述になるかと思います。
    # newアクションから入力内容を受け取り、
    # 送信ボタンを押されたらcreateアクションを実行します。
    def confirm
        @contact = Contact.new(contact_params)
        if @contact.invalid?
            render :new
        end
    end

    # 入力内容に誤りがあった場合、
    # 入力内容を保持したまま前のページに戻るのが当たり前になっているかと思いますが、
    # backアクションを定義することで可能となります。
    def back
        @contact = Contact.new(contact_params)
        render :new
    end

    # 実際に送信するアクションになります。
    # ここで初めて入力内容を保存します。
    # セキュリティーのためにも一定時間で入力内容の削除を行ってもいいかもしれません。
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            ContactMailer.send_mail(@contact).deliver_now
            redirect_to done_path
        else
            render :new
        end
    end

    # 送信完了画面を使用する場合お使いください。
    def done
    end

    private
    def contact_params
        params.require(:contact).permit(:category, :name, :organization, :email, :tel, :message, :agree)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<br>
<br>
<br>
<br>
<br>

<table>
  <tbody>
    <tr>
      <td class="text-center" style="width: 30%;">お名前</td>
      <td><%= @contact.name %></td>
    </tr>
    <tr>
      <td class="text-center">メッセージ</td>
      <td style="white-space: pre-wrap;"><%= @contact.message %></td>
    </tr>
  </tbody>
</table>

<%= form_for(@contact) do |f| %>
    <%= f.hidden_field :category %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :organization %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :tel %>
    <%= f.hidden_field :message %>
    <%= f.hidden_field :agree %>
    <div><%= f.submit '送信' %></div>
<% end %>
<%= form_for @contact, url: back_path do |f| %>
    <%= f.hidden_field :category %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :organization %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :tel %>
    <%= f.hidden_field :message %>
    <%= f.hidden_field :agree %>
    <div><%= f.submit '入力画面に戻る' %></div>
<% end %>

app/views/contacts/done.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<p id="admin_title">メールが送信されました！</p>
<p class="back"><a href="/">トップに戻る>></a></p>

app/views/contacts/new.html.erb
<main>
<div id="contact">
  <div class="page_ttl">
    <h1><span>CONTACT</span>お問い合わせ</h1>
  </div>

  <section>
    <div class="contact_form">
        <div role="form" lang="ja" dir="ltr">

        <%= form_for(@contact, url: confirm_path) do |f| %>
        <dl class="form_list">
            <dt class="form_term">お問い合わせ種別<span class="req">必須</span></dt>
            <div class="select">
                <dd class="form_description"><span data-name="your_type">
                    <%= f.select(:category, ["使い方について", "バグやエラー報告について", "その他"], { include_blank: '選択してください' }, required: true) %>
                </span></dd>
            <div class="arrow arrow_bottom"></div>
            </div>
        </dl>
        <dl class="form_list">
            <dt class="form_term">お名前<span class="req">必須</span></dt>
            <dd class="form_description"><span data-name="your_name"><%= f.text_field :name, autofocus: true, class: 'form', size: "40", maxlength: "40", placeholder: "お名前を入力してください", required: true %></span></dd>
            <p> <span class="ex">例：公園太郎</span>
        </dl>
        <dl class="form_list">
            <dt class="form_term">自治体・会社名<span class="req">必須</span></dt>
            <dd class="form_description"><span data-name="your_c_name"><%= f.text_field :organization, autofocus: true, class: 'form', size: "40", maxlength: "40", placeholder: "自治体・会社名を入力してください", required: true %></span></dd>
            <p> <span class="ex">例：株式会社PARCOM</span>
        </dl>
        <dl class="form_list">
            <dt class="form_term">メールアドレス<span class="req">必須</span></dt>
            <dd class="form_description"><span data-name="your_email"><%= f.email_field :email, autofocus: true, class: 'form', size: "40", maxlength: "40", placeholder: "メールアドレスを入力してください", required: true %></span></dd>
            <p> <span class="ex">例：admin@parcom.com</span>
        </dl>
        <dl class="form_list">
            <dt class="form_term">電話番号<span class="req">必須</span></dt>
            <dd class="form_description"><span data-name="your_tel"><%= f.text_field :tel, autofocus: true, class: 'form', size: "40", maxlength: "40", placeholder: "電話番号を入力してください", required: true %></span></dd>
            <p> <span class="ex">例：000-0000-0000</span>
        </dl>
        <dl class="form_list">
            <dt class="form_term">お問い合わせ内容<span class="req">必須</span></dt>
            <dd class="form_description"><span data-name="textarea"><%= f.text_area :message, autofocus: true, class: 'form', cols: "40", rows: "10", placeholder: "お問い合わせ内容を入力してください", required: true %></span></dd>
        </dl>

        <p class="privacy_txt">お問い合わせフォームへご入力いただいたお名前・メールアドレスなどの個人情報およびメッセージ内容は、お問い合わせの受付および回答が目的です。<br>個人情報の取り扱いについては、<%= link_to "プライバシーポリシー", "/privacy", target: :_blank, rel: "noopener noreferrer" %>をご確認ください。</p>
        <p><span data-name="privacy_check"><span><span><label id="check_label"><%= f.check_box :agree, {checked: false}, true, false %><span>プライバシーポリシーに同意します</span></label></span></span></span><br />
        <%= f.submit '送信する',id:'contact_submit' %>

          <div aria-hidden="true"></div>
        <% end %>
      </div>
    </div>
  </section>
</div>
</main>


<script>
let contact_agree = document.getElementById('contact_agree');
let check_label = document.getElementById('check_label');
let contact_submit = document.getElementById('contact_submit');
contact_submit.setAttribute("disabled", true);
contact_submit.style.backgroundColor = '#fff';
contact_submit.style.color = '#46C541';
contact_submit.style.cursor = 'auto';


check_label.addEventListener('click', function() {
  if(contact_agree.checked){
    contact_submit.removeAttribute("disabled");
    contact_submit.style.backgroundColor = '#46C541';
    contact_submit.style.color = '#fff';
    contact_submit.style.cursor = 'pointer';
  } else {
    contact_submit.setAttribute("disabled", true);
    contact_submit.style.backgroundColor = '#fff';
    contact_submit.style.color = '#46C541';
    contact_submit.style.cursor = 'auto';
  }
});
contact_submit.addEventListener('mouseover', () => {
  contact_submit.style.backgroundColor = '#fff';
  contact_submit.style.color = '#46C541';
}, false);
contact_submit.addEventListener('mouseleave', () => {
  contact_submit.style.backgroundColor = '#46C541';
  contact_submit.style.color = '#fff';
}, false);
</script>