config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'admin_sessions/new'
  root to: 'parcom#index'

  get 'sessions/new'
  resources :schedules

  # get '/zyzw', to: 'admin#index' #（例）adminログイン画面のURLを特定されない名前にする
  get '/admin_login',   to: 'admin_sessions#new'
  post '/admin_login',   to: 'admin_sessions#create'
  delete '/admin_logout',  to: 'admin_sessions#destroy'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'admin/index'
  post 'admin/index'
  get 'admin/add'
  post 'admin/add'
  get 'admin/add_done'
  get 'admin/edit'
  post 'admin/edit'
  patch 'admin/edit'
  get 'admin/delete'
  post 'admin/delete'
  get 'admin/delete_done'
  get 'admin/command'

  get 'index', to: 'parcom#index'
  get 'beginners', to: 'parcom#beginners'
  get 'help', to: 'parcom#help'
  get 'privacy', to: 'parcom#privacy'
  get 'terms', to: 'parcom#terms'
  get 'article', to: 'parcom#article'
  get 'free_wifi', to: 'parcom#free_wifi'
  get 'news', to: 'parcom#news'
  get 'park/:park_id', to: 'parcom#park'
  get 'profile/:park_id', to: 'parcom#profile'
  get 'review/:park_id', to: 'parcom#review'
  get 'parcom/get_data'
  get 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'controlpanel/:park_id/:bench_id', to: 'parcom#controlpanel'
  post 'parcom/create'
  resources :parcom, only: [:new, :create]

  get 'parcom/post_data'
  post 'parcom/post_data'
  
  get '/', to: 'parcom#index'
  post '/', to: 'parcom#index'
  get 'index', to: 'parcom#index'
  get 'register', to: 'user#register'
  post 'register', to: 'user#register'
  get 'user/create', to: 'user#create'
  post 'user/create', to: 'user#create'
  get 'account', to: 'user#account'
  post 'account', to: 'user#account'
  patch 'account', to: 'user#account'
  get 'changemail', to: 'user#changemail'
  patch 'changemail', to: 'user#changemail'
  get 'changepwd', to: 'user#changepwd'
  post 'changepwd', to: 'user#changepwd'
  patch 'changepwd', to: 'user#changepwd'
  get 'signup_success', to: 'user#signup_success'
  post 'signup_success', to: 'user#signup_success'
  get 'signupmail_success', to: 'user#signupmail_success'
  get 'signupmail', to: 'user#signupmail'
  post 'signupmail', to: 'user#signupmail'
  get 'signupmail_error', to: 'user#signupmail_error'
  get 'user/signupmail_confirm'
  post 'user/signupmail_confirm'
  post 'user/back'
  get 'changepwd_success', to: 'user#changepwd_success'
  get 'changepwd_error', to: 'user#changepwd_error'
  get 'not_activated', to: 'user#not_activated'
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/mail_done'
  get 'password_resets/mail_error'
  get 'password_resets/success'

  get 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  post 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  patch 'parkinfo_edit/:park_id', to: 'park#parkinfo_edit'
  get 'products/:park_id', to: 'park#products'
  resources :park, only: [:new, :create]
  
  get 'shortcut/:park_id', to: 'shortcut#index'
  post 'shortcut/create', to: 'shortcut#create'
  post 'shortcut/delete/:shortcut_id', to: 'shortcut#delete'

  get 'contacts', to: 'contacts#new'
  resources :contacts, only: [:create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'

  get 'analyze/:park_id', to: 'analyze#index'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, #空白を許可しない
                        length: {minimum: 8}, #最低8文字必要とする
                        on: :create
    validates :email, presence: true,
                        length: { maximum: 255 },
                        uniqueness: true
    attr_accessor  :remember_token, :activation_token, :reset_token
    before_save   :downcase_email
    before_create :create_activation_digest
    

    has_many :parks, dependent: :destroy
    has_many :bench_audios, dependent: :destroy
    has_many :bench_images, dependent: :destroy
    has_many :bench_videos, dependent: :destroy

    mount_uploader :image, ImageUploader

    

    # ランダムな記憶トークンを返す
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    # 上記２つのメソッドを利用し、生成された記憶トークンをハッシュ化
    # ハッシュ化した記憶トークンをDB（remember_digest）に保存する
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    # ユーザーのセッションをcookieに保存する（永続的セッション）
    def remember(user)
        user.remember
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
        # # cookiesに保存されたセッションに有効期限を設けたい場合（１ヶ月）
        # def remember(user)
        #     user.remember
        #     # cookies の有効期限を 1ヶ月 にしたい場合
        #     cookies.encrypted[:user_id] = { value: user.id, expires: 1.month.from_now }
        #     cookies[:remember_token] = { value: user.remember_token, expires: 1.month.from_now }
        # end
    # cookiesから渡されたトークンがダイジェスト(ハッシュ化されたトークン）と一致したらtrueを返す
    # 渡されたトークンがダイジェストと一致したらtrueを返す
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    # ユーザーの記憶ダイジェストを破棄する
    def forget
        update_attribute(:remember_digest, nil)
    end

    # 有効化用のメールを送信する
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
        update_attribute(:activation_sent_at, Time.zone.now)
    end
    # 有効化リンクの有効期限（24時間）が切れている場合はtrueを返す
    def activation_expired?
        activation_sent_at < 24.hours.ago
    end
    # アカウントを有効にする
    def activate
        update_attribute(:activated, true)
        update_attribute(:activated_at, Time.zone.now)
    end

    # パスワード再設定の属性を設定する
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    # パスワード再設定のメールを送信する
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    # パスワード再設定の有効期限が切れている場合はtrueを返す
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    private
    # メールアドレスをすべて小文字にする
    def downcase_email
        self.email = email.downcase
    end
    # 有効化トークンとダイジェストを作成及び代入する
    def create_activation_digest
        self.activation_token = User.new_token
        self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :logged_in_user, except: [:signupmail, :signupmail_success, :signupmail_confirm, :signupmail_error, :register, :signup_success, :back, :create, :not_activated]

    def index
        @parks = Park.all
    end

    def account 
        @user = User.find(current_user.id)
        if request.patch? and params[:image] then
            @user.update users_image_params
        elsif request.patch? then
            @user.update users_account_params
        end

        @parks = Park.where(user_id: current_user.id)
        p @user.image
    end

    def changemail
        logger.debug current_user.id
        @user = User.find(current_user.id)
        if request.patch? then
            @user.update users_email_params
            ChangeMailMailer.send_mail(@user).deliver_now
        end

        @parks = Park.where(user_id: current_user.id)
    end

    def changepwd
        @user = User.find(current_user.id)
        if request.patch? then
            if @user && @user.authenticate(users_password_params[:password])
                @user.update(password: users_password_params[:password_confirmation])
                redirect_to '/changepwd_success'
            else
                redirect_to '/changepwd_error'
            end
        end

        @parks = Park.where(user_id: current_user.id)
    end

    

    
    # ここで初めて入力内容を保存します。
    # セキュリティーのためにも一定時間で入力内容の削除を行ってもいいかもしれません。
    def signupmail
        @user = User.new
        if logged_in?
            render :_logged_in
        else
            if params[:user]
                @user = User.new(email: params[:user][:email])
                NewUserMailer.send_mail(@user).deliver_now
                # if
                redirect_to '/signupmail_success'
                # else
                #     redirect_to '/user/signupmail_error'
                # end //失敗したときの処理を書く？
            end
        end
    end

    def create
        if logged_in?
            render :_logged_in
        else
            @user = User.new(users_account_params)
            if @user.save
                UserMailer.account_activation(@user).deliver_now
                flash[:notice] = "アカウント有効化メールを送信しました。メールが届きましたら、記載されているリンクをクリックしてアカウントを有効化してください。"
                @user = @user.update(address: users_account_params[:prefecture] + users_account_params[:city] + users_account_params[:street])
            else
                render :new, status: :unprocessable_entity
            end
        end
    end
    
    
    def register
        if logged_in?
            render :_logged_in
        else
            @user = User.new
        end
    end

    def back
        if logged_in?
            render :_logged_in
        else
            @user = User.new(users_account_params)
            render :register
        end
    end
    
    def signupmail_confirm
        if logged_in?
            render :_logged_in
        else
            if params[:user]
                @user = User.new(users_account_params)
            end
            # if @user.invalid?
            #     render :register
            # else
            #     @user = User.create users_account_params
            # end
        end
    end

    def signupmail_success
        if logged_in?
            render :_logged_in
        end
    end

    def signupmail_error
        if logged_in?
            render :_logged_in
        end
    end

    def signup_success #ここでUserモデルに許可を出す＝アカウント作成（必須項目だけ）
        
    end

    private
    def users_account_params
        params.require(:user).permit(:name, :email, :password, :zip,  :prefecture, :city, :street, :tel, :municipality, :division, :profile, :image)
    end

    private
    def users_email_params
        params.require(:user).permit(:email)
    end

    private
    def users_password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

    private
    def users_image_params
        params.require(:user).permit(:image)
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_logged_in.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div id="login">
<div id="login_related">
    <div class="inner_min">
    <div class="logo">
        <%= image_tag "/common/os-logo.svg", alt: "PARCOM OS" %>
    </div>
    <div class="login_related_content">
        <h1>ログインしています。</h1>
        <%= link_to "トップページへ", '/', class:'btn' %>
    </div>
    </div>
</div>
</div>

app/views/user/_not_logged_in.html.erb
<main>
<div id="signup">
<div id="login_related">
  <div class="inner_min">
    <div class="logo">
      <%= image_tag "/common/os-logo.svg", alt: "PARCOM OS" %>
    </div>
    <div class="login_related_content">
      <h1>アカウント登録</h1>
      <div class="step_content">
        <div class="step_item active">
          <div class="step_item_num">1</div>
          <span>入力</span>
        </div>
        <div class="step_item">
          <div class="step_item_num">2</div>
          <span>確認</span>
        </div>
        <div class="step_item">
          <div class="step_item_num">3</div>
          <span>完了</span>
        </div>
      </div>
      <form id="" name="">
                <p id="submit_failed" class="caution" style="display:none;"><%= image_tag "/signin_warning.png" %>メールアドレスまたはパスワードが空欄です</p>
      	<div class="txt_field">
          <dt class="form_term">メールアドレス</dt>
      		<dd class="form_description"><input type="text" name="log" id="login_email" value="" placeholder="メールアドレスを入力してください"></dd>
      	</div>
        <div class="txt_field">
          <dt class="form_term">アカウント名</dt>
      		<dd class="form_description"><input type="text" name="log" id="login_name" value="" placeholder="アカウント名を入力してください"></dd>
      	</div>
      	<div class="txt_field">
          <dt class="form_term">パスワード</dt>
      		<dd class="form_description"><input type="password" name="pwd" id="login_password" value="" placeholder="パスワードを入力してください"></dd>
          <span class="ex">6〜20文字・半角英数</span>
      	</div>
      	<input class="btn" id="" name="" type="button" value="内容を確認する">
      </form>
    </div>
  </div>
</div>
</main>

app/views/user/account.html.erb
<main>
<div id="account_edit">
<div class="wrap flex_container_start">
  <div class="menu-trigger tab_sp" href="javascript:void(0);">
	<span class="spnavButton__border"></span>
	<span class="spnavButton__border"></span>
	<span class="spnavButton__border"></span>
</div>
<%= render partial: "shared/aside" %>
  <div id="account_related" class="inner_mid">
    <div class="page_ttl_wrap">
      <div class="page_ttl">
        <h1>アカウント情報</h1>
      </div>
    </div>
    <div class="content">
      <div class="content_frame">
        <div class="account_item account_item_ttl">
          <dt><h2>基本情報の変更</h2></dt>
          <dd>一部の情報はGoogleのサービスと連携されています。<a href="">詳細</a></dd>
        </div>
        <div class="account_form_wrap">
          <div class="prof_img_edit flex_container">
            <div>
              <dt class="form_term">プロフィール画像<span class="any">任意</span></dt>
              <dd class="form_description">アカウントの基本情報を確認・管理・変更することが可能です。<a href="">詳細</a></dd>
            </div>
            <div>
              <label id="upload_box">
                <div id="upload_form">
                  <%= form_for(@user, url:{controller:'user', action:'account'}) do |form| %>
                    <%= form.file_field :image, id:'img_file', accept:'image/*' %>
                    <%= form.submit "写真を追加", id:'add_picture_submit' %>
                  <% end %>
                </div>
              </label>
              <% if @user.image.to_s != "" %>
                <%= image_tag @user.image.to_s, class: "icon", id:"user_image" %>
              <% else %>
                <%= image_tag "/common/icon_owner_default.svg", class: "icon", id:"user_image" %>
              <% end %>
            </div>
          </div>
          <%= form_for(@user, url:{controller:'user', action:'account'}) do |form| %>
            <div class="txt_field">
              <dt class="form_term">ユーザーネーム<span class="req">必須</span></dt>
              <dd class="form_description"><%= form.text_field :name, placeholder:"ユーザーネーム", required: true %></dd>
            </div>
            <div class="txt_field">
              <dt class="form_term">自治体名<span class="req">必須</span></dt>
              <dd class="form_description"><%= form.text_field :municipality, placeholder:"〇〇市", required: true %></dd>
            </div>
            <div class="txt_field">
              <dt class="form_term">所属<span class="req">必須</span></dt>
              <dd class="form_description"><%= form.text_field :division, placeholder:"公園緑地課", required: true %></dd>
            </div>
            <%= form.submit "この内容で変更する", class:"btn btn_g" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="cover"></div>
</main>

<script>
  const user_image = document.getElementById('user_image');
  const upload_box = document.getElementById('upload_box');
  const cover = document.getElementById('cover');

  user_image.addEventListener('click', function() {
	upload_box.style.display = 'block';
	cover.style.display = 'block';
  });
  cover.addEventListener('click', function() {
    upload_box.style.display = 'none';
    cover.style.display = 'none';
  });
  
</script>

app/views/user/changemail.html.erb
<main>
<div id="changemail">
<div class="wrap flex_container_start">
  <div class="menu-trigger tab_sp" href="javascript:void(0);">
	<span class="spnavButton__border"></span>
	<span class="spnavButton__border"></span>
	<span class="spnavButton__border"></span>
</div>

<%= render partial: "shared/aside" %>
  <div id="account_related" class="inner_mid">
    <div class="page_ttl_wrap">
      <div class="page_ttl">
        <h1>ログイン情報</h1>
      </div>
    </div>
    <div class="content">
      <div class="content_frame">
        <div class="account_item account_item_ttl">
          <dt><h2>メールアドレスの変更</h2></dt>
          <dd>ダミーテキストダミーテキストダミーテキストダミーテキスト<a href="">詳細</a></dd>
        </div>
        <div class="account_form_wrap">
          <%= form_for(@user, url:{controller:'user', action:'changemail'}) do |form| %>
            <div class="txt_field">
              <dt class="form_term">メールアドレス<span class="req">必須</span></dt>
              <dd class="form_description"><%= form.email_field :email, placeholder:"admin@parcom.jp", required: true %></dd>
            </div>
            <%= form.submit "確認メールを送信する", class: "btn btn_g" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</main>
    

app/views/user/changepwd.html.erb
<main>
<div id="changepwd">
<div class="wrap flex_container_start">
  <div class="menu-trigger tab_sp" href="javascript:void(0);">
	<span class="spnavButton__border"></span>
	<span class="spnavButton__border"></span>
	<span class="spnavButton__border"></span>
</div>

<%= render partial: "shared/aside" %>
  <div id="account_related" class="inner_mid">
    <div class="page_ttl_wrap">
      <div class="page_ttl">
        <h1>ログイン情報</h1>
      </div>
    </div>
    <div class="content">
      <div class="content_frame">
        <div class="account_item account_item_ttl">
          <dt><h2>パスワードの変更</h2></dt>
          <dd>ダミーテキストダミーテキストダミーテキストダミーテキスト<a href="">詳細</a></dd>
        </div>
        <div class="account_form_wrap">
        <%= form_for(@user, url:{controller:'user', action:'changepwd'}) do |form| %>
            <div class="txt_field">
              <dt class="form_term">現在のパスワード<span class="req">必須</span></dt>
              <dd class="form_description"><%= form.password_field :password, placeholder:"現在のパスワードを入力", required: true %></dd>
              <span class="ex"><%= link_to "現在のパスワードをお忘れですか？", new_password_reset_path %></span>
            </div>
            <div class="txt_field">
              <dt class="form_term">新しいパスワード<span class="req">必須</span></dt>
              <dd class="form_description"><%= form.password_field :password_confirmation, placeholder:"新しいパスワードを入力",type: "password", required: true, id: "new_password" %></dd>
              <span class="ex">半角英数字8文字以上</span>
            </div>
            <div class="txt_field">
              <dt class="form_term">新しいパスワード（確認用）<span class="req">必須</span></dt>
              <dd class="form_description"><%= form.password_field :password_confirmation, type: "password", required: true, id: "new_password_confirm" %></dd>
              <span class="ex">上と同じパスワードを入力してください</span>
              <p id="match_message">パスワードが一致していません。</p>
            </div>
            <div id="update_btn_filter"></div>
            <%= form.submit "パスワードを変更する", class: "btn btn_g", id:"update_btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</main>
<script>
let new_password = document.getElementById('new_password');
let new_password_confirm = document.getElementById('new_password_confirm');
let match_message = document.getElementById('match_message');
let update_btn_filter = document.getElementById('update_btn_filter');
let update_btn = document.getElementById('update');

new_password.addEventListener('change', function() {
    judgeMatch();
});
new_password_confirm.addEventListener('change', function() {
    judgeMatch();
});

function  judgeMatch() {
    if(new_password.value == new_password_confirm.value){
      match_message.textContent = '';
      update_btn_filter.style.display = 'none';
    } else {
      match_message.textContent = 'パスワードが一致していません。';
      update_btn_filter.style.display = 'block';
    }
}
</script>

app/views/user/changepwd_error.html.erb
<br>
<br>
<br>
<br>
<br>
<p>問題が発生しました。もう一度やり直してください。</p>

app/views/user/changepwd_success.html.erb
<br>
<br>
<br>
<br>
<br>
<p>パスワードが変更されました。</p>

app/views/user/create.html.erb
<main>
<div id="signup_success">
<div id="login_related">
  <div class="inner_min">
    <div class="logo">
      <%= image_tag "/common/os-logo.svg", alt: "PARCOM OS" %>
    </div>
    <div class="login_related_content">
      <h1>アカウント有効化手続き</h1>
      <div class="step_content step_content_success">
        <div class="step_item active">
          <div class="step_item_num"><%= image_tag "/common/icon_success.svg" %></div>
          <span>入力</span>
        </div>
        <div class="step_item">
          <div class="step_item_num"><%= image_tag "/common/icon_success.svg" %></div>
          <span>確認</span>
        </div>
        <div class="step_item">
          <div class="step_item_num">3</div>
          <span>完了</span>
        </div>
      </div>
      <div class="signup_success_txt">
        <p>メールを送信しました。確認してアカウントの有効化手続きを行ってください。</p>
      </div>
    </div>
  </div>
</div>
</main>

app/views/user/index.html.erb
<% if logged_in? %>
  <%= render 'user/logged_in' %>
<% else %>
  <%= render 'user/not_logged_in' %>
<% end %>

app/views/user/register.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<p id="admin_title">アカウント登録ページです。</p>

<div id="user">
<%= form_for(@user, url:{controller:'user', action:'signupmail_confirm'}) do |form| %>
    <div class="form-group">
        <label for="name">表示名（必須）</label>
        <%= form.text_field :name, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="email">メールアドレス（必須）</label>
        <%= form.email_field :email, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="password">パスワード（必須）</label>
        <%= form.text_field :password, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="zip">郵便番号（必須）</label>
        <%= form.text_field :zip, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="prefecture">住所(都道府県)（必須）</label>
        <%= form.text_field :prefecture, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="city">住所(市区町村)（必須）</label>
        <%= form.text_field :city, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="street">それ以降の住所（必須）</label>
        <%= form.text_field :street, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="tel">電話番号（必須）</label>
        <%= form.text_field :tel, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="municipality">自治体名（必須）</label>
        <%= form.text_field :municipality, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="division">所属課（必須）</label>
        <%= form.text_field :division, class:"form", required: true %>
    </div>
    <div class="form-group">
        <label for="profile">プロフィール内容（必須）</label>
        <%= form.text_field :profile, class:"form", required: true %>
    </div>
    <%= form.submit "作成" %>
<% end %>
</div>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/user/signupmail.html.erb
<main>
<div id="signupmail">
<div id="login_related">
  <div class="inner_min">
    <div class="logo">
      <%= image_tag "/common/os-logo.svg", alt: "PARCOM OS" %>
    </div>
    <div class="login_related_content">
      <h1>アカウントを作成する</h1>
        <%= form_for(@user, url:{controller:'user', action:'signupmail'}, name:"pre_register", local:true) do |f| %>
        <!--
        <p id="submit_failed" class="caution" style="display:none;"><%= image_tag "/signin_warning.png" %>メールアドレスまたはパスワードが空欄です</p>
        -->
      	<div class="txt_field">
          <dt class="form_term">メールアドレス</dt>
      		<dd class="form_description"><%= f.email_field :email, autofocus: true, id:"login_email", size: "40", placeholder: "メールアドレスを入力してください" %></dd>
          <span class="ex">アカウントを作成することにより、<%= link_to "利用規約", "/terms" %>および<%= link_to "プライバシーポリシー", "/privacy" %>を読み、これに同意するものとします。</span>
      	</div>
        <%= f.submit '仮登録メールを送信する', class:"btn" %>
      <% end %>
    </div>
    <div class="new_signup_wrap">
      <p>PARCOM ADMINのアカウントをすでにお持ちですか？<br><%= link_to "ログインはこちら",controller:'parcom', action:'index' %></p>
    </div>
  </div>
</div>
</main>

app/views/user/signupmail_confirm.html.erb
<br>
<br>
<br>
<br>
<br>


<% if @user %>
    <p id="admin_title">この内容で登録してもよろしいですか？</p>
    <p>アカウント名: <%= @user.name %></p>
    <p>メールアドレス: <%= @user.email %></p>
    <p>郵便番号: <%= @user.zip %></p>
    <p>都道府県: <%= @user.prefecture %></p>
    <p>市町村: <%= @user.city %></p>
    <p>それ以降の住所: <%= @user.street %></p>
    <p>電話番号: <%= @user.tel %></p>
    <p>自治体名: <%= @user.municipality %></p>
    <p>所属課: <%= @user.division %></p>
    <p>プロフィール内容: <%= @user.profile %></p>
    <%= form_for(@user, url:{controller:'user', action:'create'}) do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :password %>
        <%= f.hidden_field :zip %>
        <%= f.hidden_field :prefecture %>
        <%= f.hidden_field :city %>
        <%= f.hidden_field :street %>
        <%= f.hidden_field :tel %>
        <%= f.hidden_field :municipality %>
        <%= f.hidden_field :division %>
        <%= f.hidden_field :profile %>
        <div><%= f.submit '送信' %></div>
    <% end %>

    <%= form_for(@user, url:{controller:'user', action:'back'}) do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :password %>
        <%= f.hidden_field :zip %>
        <%= f.hidden_field :prefecture %>
        <%= f.hidden_field :city %>
        <%= f.hidden_field :street %>
        <%= f.hidden_field :tel %>
        <%= f.hidden_field :municipality %>
        <%= f.hidden_field :division %>
        <%= f.hidden_field :profile %>
        <div><%= f.submit '入力画面に戻る' %></div>
    <% end %>
<% else %>
    <p id="admin_title">申し訳ありませんが、こちらのリンクからやり直してください。</p>
    <%= link_to "登録画面へ戻る", '/register' %>
<% end %>

app/views/user/signupmail_error.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<p id="admin_title">エラーが起きました。もう一度やり直してください。</p>
<p class="back"><a href="/register">登録画面に戻る>></a></p>

app/views/user/signupmail_success.html.erb
<main>
<div id="signupmail_success">
<div id="login_related">
  <div class="inner_min">
    <div class="logo">
      <%= image_tag "/common/os-logo.svg", alt: "PARCOM OS" %>
    </div>
    <div class="login_related_content">
      <div class="signupmail_success">
        <h1>アカウント仮登録完了</h1>
        <div class="signupmail_success_txt">
          <p>本人確認メールを送信しました。</p>
          <p>ご登録いただいたメールアドレス宛に本登録メールをお送りいたしました。メール本文に記載されているURLを押してアカウント登録を完了させてください。</p>
        </div>
        <div class="signupmail_success_mail">
          <p>メールが届かない場合</p>
          <ul>
            <li>迷惑メールフォルダ等に振り分けられていないかご確認ください。</li>
            <li>携帯メールアドレスの場合、ドメイン設定によりメールが受信できない場合がございます。「ドメイン名」を受信許可リストに設定の上、<%= link_to "こちら", action:'signupmail' %>からメールを再送してください。</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</main>